name: Bug Report 🐞
description: Help us squash those bugs!
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us make KiddyCode better! Let's find and fix those bugs together! 🐛
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what went wrong and what you expected to happen.
      placeholder: Describe the bug here!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of KiddyCode are you using?
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Show us the code that caused the bug. Let's see if we can spot the problem!
      render: kiddy
  - type: textarea
    id: logs
    attributes:
      label: Any error messages?
      description: Copy and paste any error messages you saw. This helps us understand what went wrong.
      render: shell